### ISSUE TITLE
[BUG] Nudge Tool: Nudging "Pasted" pixels (from Marquee Tool) reveals them.

### ISSUE THREAD

**Issue by chamberlainpi** [Danik/Pyxel-Edit#10]
After moving a selection with the Marquee Tool, try nudging the tile where the pasted-pixels would of been (current bug doesn't reveal them).
Notice how the nudge tool seems to reveal the pixels.

**Comment by Danik** [comment]
Related to canvas not updating when using selection tool, which has been fixed.
