### ISSUE TITLE
[FEATURE] Resize canvas: Have Plus (+) and Minus (-) buttons instead of Numeric Steppers for each sides.

### ISSUE THREAD

**Issue by chamberlainpi** [Danik/Pyxel-Edit#19]
Instead of Numeric-Steppers, maybe some +/- buttons beside each ones would work better (I've accidentally decreased / increased when I wanted to change the value the other way around)

**Comment by Danik** [comment]
The canvas resize dialog has been fully redesigned to be clearer and easier to use. Closing unless issue persists.
