### ISSUE TITLE
[FEATURE] Shortcuts: Play current animation.

### ISSUE THREAD

**Issue by chamberlainpi** [Danik/Pyxel-Edit#25]
Have a keyboard shortcut for "Play" / "Pause" would be nice.
Um... but since SPACE is already used for panning the stage, maybe CTRL+SPACE could work? Or CTRL+ENTER (since that's almost a reflex for more Flash developers to compile / launch their animations)

**Comment by Danik** [comment]
Implemented using Ctrl+Space.
