### ISSUE TITLE
[FEATURE] Export tileset: Use animation names as filename prefix for PNG sequence.

### ISSUE THREAD

**Issue by chamberlainpi** [Danik/Pyxel-Edit#28]
When exporting animations to separate files, it would be nice to be able to have the option to use the animation names (defined in the list of animations) as the PNG Sequence's filename prefix.

As it is now, all the tiles from the Tileset use the same name entered in the "Save path" field. Then, they have to be manually renamed... and this needs to be done each time they're corrected / re-exported. Not fun!

**Comment by Danik** [comment]
Would you say they should still have the sequence numbers, or only the animation names?
I guess only having the animation names would be more flexible since the user can specify the exact filename from the animation name.

**Comment by chamberlainpi** [comment]
Hmm, well I guess this is a tricky part.

If I'm thinking the way I assume you've implemented tilesets / tiles / animations, you probably don't have a solid variable reference to know how each tiles (from the tileset) are tied to an animation, since each tiles could be reused in several different animations... So... I guess the "Export tileset" export dialog box may not be the best place for this. Maybe this is more of an option for the "Export animation(s)" export dialog box... hmm.

Either way, it would be good to export separate tiles of an animation, in the format: path/animationname_00, path/animationname_01, path/animationname_02, etc.

I guess, as I shown actually in my demo video (where frame 2 = frame 4), similar frames would be exported regardless, which isn't a big deal since TexturePacker can recognize similar images and merge them as one.

So maybe this is more of an "Export animation(s)" option, in the end. What do you think?

**Comment by Danik** [comment]
Aha, now I see what you mean.
Perhaps there should be a separate tab in the Export animations dialog besides "Spritesheet" and "Animated GIF" named something like "Individual frames", where you can export one or all animations as separate files per frame with names like "givenName_animName_01".

**Comment by chamberlainpi** [comment]
Yeah! That would work for sure. I'm all for a 3rd tab dedicated to this functionality. I personally wouldn't really be needing the "givenName_" PRE-prefix, but if a filename is mandatory to begin with, then it's no problem!

I guess it would be useful to organize all the animations of one entity / character in the same pyxeledit document, and export as "joeblow_walkCycle_01", etc. So yeh your suggested filename format would work fine.

**Comment by Danik** [comment]
Implemented!
