### ISSUE TITLE
[FEATURE] Export tileset: Use double-digits (or custom even) to keep file-ordering intact.

### ISSUE THREAD

**Issue by chamberlainpi** [Danik/Pyxel-Edit#30]
When exporting animations to separate files, using double-digits (ex: 00) would be helpful since when importing the PNG sequence into TexturePacker, and using in Starling, the order of the textures breaks if they're not padded to the largest number length.
Example:
WRONG = "player_10, player_11, player_12" will come first before "player_0, player_1, player_2"
RIGHT = "player_00, player_01, player_02" will come first before "player_10, player_11, player_12"

**Comment by Danik** [comment]
Implemented.
