### ISSUE TITLE
[BUG] Export tilemap: JSON format is missing tileswide, tileshigh, tilewidth, tileheight

### ISSUE THREAD

**Issue by chamberlainpi** [Danik/Pyxel-Edit#31]
When exporting JSON format, it's missing some properties normally included in the XML format:
tileswide, tileshigh, tilewidth, tileheight

**Comment by Danik** [comment]
Fixed.

**Comment by chamberlainpi** [comment]
Ah nice! Can't wait for the next release with this fix :D any idea when it'll be available?
