### ISSUE TITLE
[BUG] Unknown file format message while opening png file with uppercase extension

### ISSUE THREAD

**Issue by unlucky-cat** [Danik/Pyxel-Edit#34]
Attempt to open PNG file with uppercase extension .PNG leads to error message "The image format was not recognized"

![image](https://cloud.githubusercontent.com/assets/1206629/12099103/1076ea10-b32f-11e5-826b-35bbf22a625b.png)

Changing file format to lowercase solves the problem.

**Comment by Danik** [comment]
Fixed in 0.3.109PR2
