### ISSUE TITLE
[BUG] Marquee Tool: Disappearing pasted-pixels, also turns out blank from source selection.

### ISSUE THREAD

**Issue by chamberlainpi** [Danik/Pyxel-Edit#6]
When dragging a selection the 1st time, the pixels do move with it (like it should).
But select the same region right after, notice how the previously pasted pixels disappears. (related to another bug - https://github.com/Danik/Pyxel-Edit/issues/5).
The 2nd time you select the pixels (from the region made the 1st time), it copies ""blank"" pixels (try dragging it), instead of the desired pixels in the selection.

**Comment by Danik** [comment]
Related to canvas not updating when using selection tool, which has been fixed.
