### ISSUE TITLE
[BUG] Nudge Tool: Nudging the tile on Marquee Tool's source region clears the pixels.

### ISSUE THREAD

**Issue by chamberlainpi** [Danik/Pyxel-Edit#9]
After moving a selection with the Marquee Tool, try nudging the pixels in the tile where you made your initial selection.
Notice that the region of "moved" pixels disappeared, only the remaining pixels stayed in the actual tile's data.

**Comment by Danik** [comment]
Related to canvas not updating when using selection tool, which has been fixed.
